# Conv SE context ONNX
[model]
model_path = ../../model_convert/quant/onnx_models/conv_se_context.onnx
model_type = mask_batch

[params]
hop_len = 256
t_model = 64
f_freqs = 257
f_int = 129
step = 6

