# Official GTCRN 7-input less-input no-scatter ONNX
[model]
model_path = ../../model_convert/quant/onnx_models/gtcrn_no_scatter_less_input_optimized.onnx
model_type = gtcrn_stream

[params]
hop_len = 256
t_model = 1
f_freqs = 257
f_int = 257
step = 1

